### ISSUE TITLE
EXAMPLE_SUPPORT* and EXAMPLE_EPICS_BASE* not needed

### ISSUE THREAD

**Issue by MarkRivers** [EPICS-synApps/configure#8]
The old mechanism we were using for being able to build synApps on Windows and Linux in the same tree was to have all module RELEASE files have these lines:
```
-include $(TOP)/../configure/SUPPORT.$(EPICS_HOST_ARCH)
-include $(TOP)/../configure/EPICS_BASE.$(EPICS_HOST_ARCH) 
```
This is no longer the approved method to do this.  Now all module RELEASE files contain these lines.
```
-include $(TOP)/../RELEASE.local
-include $(TOP)/../RELEASE.$(EPICS_HOST_ARCH).local
-include $(TOP)/configure/RELEASE.local
```
$(TOP)/../RELEASE.$(EPICS_HOST_ARCH).local can define SUPPORT and EPICS_BASE differently for Windows.

I have this removed all of the EXAMPLE_SUPPORT* and EXAMPLE_EPICS_BASE* files from the top-level support/configure directory.  In their place I have added the following files to the top-level support directory.
```
EXAMPLE_RELEASE.win32-x86-static.local
EXAMPLE_RELEASE.win32-x86.local
EXAMPLE_RELEASE.windows-x64-static.local
EXAMPLE_RELEASE.windows-x64.local
```

**Comment by keenanlang** [comment]
Fixed with 4f10219 and dba65d8
